# 21. Numpy 

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

    [numpy tutorial](https://numpy.org/devdocs/user/quickstart.html)

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import sys
import numpy as np
print("python {}".format(sys.version))
print("numpy {}".format(np.__version__))
sys.version
np.__version__

python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
numpy 1.18.1


'1.18.1'

In [4]:
# 스칼라
x = 6
x

6

In [5]:
# array
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
x.shape

(3,)

### matrix

In [30]:
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)
print(y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### np.random

In [8]:
z = np.random.randint(10, size=6)
z

array([1, 0, 6, 7, 0, 6])

In [9]:
z[0]

1

In [10]:
z[:2]

array([1, 0])

In [11]:
z[-1]

6

In [12]:
z.min()

0

In [13]:
z.max()

7

In [14]:
z.mean()

3.3333333333333335

In [15]:
z < 6

array([ True,  True, False, False,  True, False])

In [16]:
z > 8

array([False, False, False, False, False, False])

In [17]:
z[z > 8]

array([], dtype=int32)

In [18]:
z.sort()
z

array([0, 0, 1, 6, 6, 7])

In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
a + b

array([ 7,  9, 11, 13, 15])

In [20]:
a + 30

array([31, 32, 33, 34, 35])

In [21]:
b - 10

array([-4, -3, -2, -1,  0])

In [22]:
c = a * b
c

array([ 6, 14, 24, 36, 50])

In [25]:
print("Mean: ", np.mean(c), "\nStandard Deviation: ", np.std(c))

Mean:  26.0 
Standard Deviation:  15.646085772486357


In [28]:
N = 10  
weights = np.random.uniform(0, 1, N)
weights = weights/np.sum(weights)   
weights

array([0.03905471, 0.21597825, 0.11661641, 0.00861672, 0.16701719,
       0.12492773, 0.09998301, 0.18227184, 0.03335578, 0.01217835])

## Slicing


<img src="numpy1.png" width="300">


<img src="numpy.png" width="500">

In [9]:
A = np.ones((3, 3, 3)) 

In [10]:
A[0, 1] = 2
A

array([[[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
A[:, 0] = 3
A

array([[[3., 3., 3.],
        [2., 2., 2.],
        [1., 1., 1.]],

       [[3., 3., 3.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[3., 3., 3.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
A[:] = 5
A

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [13]:
A[:, :, 0] = 3
A

array([[[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 5.]],

       [[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 5.]],

       [[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 5.]]])

In [14]:
A[2, 2, 2] = 9
A

array([[[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 5.]],

       [[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 5.]],

       [[3., 5., 5.],
        [3., 5., 5.],
        [3., 5., 9.]]])

In [17]:
A[-1, -1, -1] = -1
A

array([[[ 3.,  5.,  5.],
        [ 3.,  5.,  5.],
        [ 3.,  5.,  5.]],

       [[ 3.,  5.,  5.],
        [ 3.,  5.,  5.],
        [ 3.,  5.,  5.]],

       [[ 3.,  5.,  5.],
        [ 3.,  5.,  5.],
        [ 3.,  5., -1.]]])